// SPDX-License-Identifier: Apache-2.0
#pragma once
#include <stdint.h>
namespace hypertweak::native {
// LSPosed reports RTLD_NOLOAD queries as library notifications too. This scope
// covers the whole query, including its synchronous framework callbacks.
inline thread_local uint32_t g_native_rule_query_depth = 0u;
class NativeRuleLibraryQuery {
 public:
    NativeRuleLibraryQuery() { ++g_native_rule_query_depth; }
    ~NativeRuleLibraryQuery() { --g_native_rule_query_depth; }
};
inline bool NativeRuleLibraryQueryActive() { return g_native_rule_query_depth != 0u; }

// Protected by the runtime mutex. A completed generation sleeps until an actual
// configuration/image change. Failures retry only on external events, never on
// a timer or a callback generated by the preparation itself.
struct NativeRulePreparationGate {
    uint64_t generation = 1u;
    uint64_t running_generation = 0u;
    uint64_t retry_after = 0u;
    uint32_t attempts = 0u;
    bool needed = true;
    bool queued = false;
    bool running = false;
    void Changed() { ++generation; needed = true; attempts = 0u; retry_after = 0u; }
    bool Queue(uint64_t now) {
        if (NativeRuleLibraryQueryActive() || !needed || queued || running ||
            attempts >= 3u || now < retry_after) return false;
        queued = true;
        return true;
    }
    void Begin() { queued = false; running = true; running_generation = generation; }
    void Complete(uint64_t now, bool success) {
        running = false;
        if (generation != running_generation) return;
        if (success) needed = false;
        else { ++attempts; retry_after = now + 1000000000ull; }
    }
};
}
